### ISSUE TITLE
support relative paths with wapc codegen configuration

### ISSUE THREAD

**Issue by jsoverson** [wapc/cli#9]
The install & generate commands seem to only accept either npm packages, gh repos, or absolute file paths which makes it difficult to develop with.

It would be great to support relative file paths (relative to the configuration file), e.g.

```yaml
schema: schema.widl
generates:
  src/generated.rs:
    module: "../codegen"
    visitorClass: ModuleVisitor
```
